#include "timeline/effects_editor.h"
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace ytp { namespace {
TimelineItem* editableItem(Sequence& sequence, std::string_view id) {
    auto* item = sequence.findItem(id);
    const auto* track = item ? sequence.findTrack(item->trackId) : nullptr;
    if (!item || !track || track->locked) return nullptr;
    return item;
}

std::vector<EffectInstance>* chain(Sequence& sequence,EffectTarget target,std::string_view id){
    if(target==EffectTarget::Master)return &sequence.masterEffects;
    if(target==EffectTarget::Track){auto* t=sequence.findTrack(id);return t&&!t->locked?&t->effects:nullptr;}
    auto* item=editableItem(sequence,id);return item?&item->effects:nullptr;
}
EffectInstance* effect(Sequence& s,EffectTarget t,std::string_view id,std::string_view effectId){auto*c=chain(s,t,id);if(!c)return nullptr;auto it=std::find_if(c->begin(),c->end(),[effectId](auto&e){return e.id==effectId;});return it==c->end()?nullptr:&*it;}
}
void EffectsEditor::setTransform(Sequence&s,std::string_view id,TransformSettings value){if(validateTransform(value))throw std::invalid_argument("invalid transform");auto*i=editableItem(s,id);if(!i)throw std::invalid_argument("item missing or locked");i->transform=value;}
Id EffectsEditor::addTransformKeyframe(Sequence&s,std::string_view id,std::string_view property,Rational time,double value,KeyframeInterpolation interpolation){auto*i=editableItem(s,id);double minimum=-100000,maximum=100000;if(property=="scaleX"||property=="scaleY"){minimum=.001;maximum=1000;}else if(property=="rotation"){minimum=-36000;maximum=36000;}else if(property=="opacity"){minimum=0;maximum=1;}else if(property!="positionX"&&property!="positionY")throw std::invalid_argument("transform keyframe property invalid");if(!i||time<Rational{}||time>i->duration||!std::isfinite(value)||value<minimum||value>maximum)throw std::invalid_argument("transform keyframe invalid");auto&channels=i->transform.animation;auto found=std::find_if(channels.begin(),channels.end(),[property](auto&p){return p.name==property;});if(found==channels.end()){channels.push_back({.name=std::string(property),.value=value,.minimum=minimum,.maximum=maximum,.unit={},.keyframes={}});found=std::prev(channels.end());}auto existing=std::find_if(found->keyframes.begin(),found->keyframes.end(),[time](auto&k){return k.time==time;});if(existing!=found->keyframes.end()){existing->value=value;existing->interpolation=interpolation;return existing->id;}Keyframe key{.id=createId(),.time=time,.value=value,.interpolation=interpolation};auto result=key.id;found->keyframes.push_back(std::move(key));std::sort(found->keyframes.begin(),found->keyframes.end(),[](auto&a,auto&b){return a.time<b.time;});return result;}
void EffectsEditor::setClipAudio(Sequence&s,std::string_view id,AudioSettings value){if(validateAudio(value))throw std::invalid_argument("invalid audio");auto*i=editableItem(s,id);if(!i)throw std::invalid_argument("item missing or locked");i->audio=std::move(value);}
void EffectsEditor::setTrackAudio(Sequence&s,std::string_view id,AudioSettings value){if(validateAudio(value))throw std::invalid_argument("invalid audio");auto*t=s.findTrack(id);if(!t||t->locked)throw std::invalid_argument("track missing or locked");t->audio=std::move(value);}
void EffectsEditor::setMasterAudio(Sequence&s,AudioSettings value){if(validateAudio(value))throw std::invalid_argument("invalid audio");s.masterAudio=std::move(value);}
Id EffectsEditor::addAudioKeyframe(Sequence&s,EffectTarget target,std::string_view id,std::string_view parameter,Rational time,double value,KeyframeInterpolation interpolation){if(parameter!="gain"&&parameter!="pan")throw std::invalid_argument("audio keyframe parameter invalid");AudioSettings*a=nullptr;Rational maximumTime;bool bounded=false;if(target==EffectTarget::Master)a=&s.masterAudio;else if(target==EffectTarget::Track){auto*t=s.findTrack(id);if(t&&!t->locked)a=&t->audio;}else{auto*i=editableItem(s,id);if(i){a=&i->audio;maximumTime=i->duration;bounded=true;}}if(!a||time<Rational{}||(bounded&&time>maximumTime)||(parameter=="gain"&&(value < -96||value>24))||(parameter=="pan"&&(value < -1||value>1))||!std::isfinite(value))throw std::invalid_argument("audio keyframe invalid");auto&keys=parameter=="gain"?a->gainEnvelope:a->panEnvelope;auto found=std::find_if(keys.begin(),keys.end(),[time](auto&k){return k.time==time;});if(found!=keys.end()){found->value=value;found->interpolation=interpolation;return found->id;}Keyframe key{.id=createId(),.time=time,.value=value,.interpolation=interpolation};auto result=key.id;keys.push_back(std::move(key));std::sort(keys.begin(),keys.end(),[](auto&a,auto&b){return a.time<b.time;});return result;}
Id EffectsEditor::addEffect(Sequence&s,EffectTarget t,std::string_view id,std::string_view type){auto*c=chain(s,t,id);const auto*d=findEffectDescriptor(type);if(!c||!d)throw std::invalid_argument("target missing");if(t==EffectTarget::Master&&!d->audio)throw std::invalid_argument("master accepts audio effects");if(t==EffectTarget::Track){const auto*track=s.findTrack(id);if(!track||d->audio!=(track->kind==TrackKind::Audio))throw std::invalid_argument("effect and track kinds differ");}if(t==EffectTarget::Item){const auto*item=s.findItem(id);const auto*track=item?s.findTrack(item->trackId):nullptr;if(!track||d->audio!=(track->kind==TrackKind::Audio))throw std::invalid_argument("effect and item kinds differ");}auto value=createEffect(type);auto result=value.id;c->push_back(std::move(value));return result;}
void EffectsEditor::removeEffect(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId){auto*c=chain(s,t,id);if(!c)throw std::invalid_argument("target missing");const auto n=c->size();std::erase_if(*c,[effectId](auto&e){return e.id==effectId;});if(n==c->size())throw std::invalid_argument("effect missing");}
void EffectsEditor::moveEffect(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId,int offset){auto*c=chain(s,t,id);if(!c)throw std::invalid_argument("target missing");auto it=std::find_if(c->begin(),c->end(),[effectId](auto&e){return e.id==effectId;});if(it==c->end())throw std::invalid_argument("effect missing");auto from=static_cast<int>(std::distance(c->begin(),it));auto to=std::clamp(from+offset,0,static_cast<int>(c->size())-1);if(from!=to){auto value=std::move((*c)[from]);c->erase(c->begin()+from);c->insert(c->begin()+to,std::move(value));}}
void EffectsEditor::setEffectEnabled(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId,bool enabled){auto*e=effect(s,t,id,effectId);if(!e)throw std::invalid_argument("effect missing");e->enabled=enabled;}
void EffectsEditor::resetEffect(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId){auto*e=effect(s,t,id,effectId);if(!e)throw std::invalid_argument("effect missing");const auto originalId=e->id;*e=createEffect(e->type);e->id=originalId;}
void EffectsEditor::setParameter(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId,std::string_view name,double value){auto*e=effect(s,t,id,effectId);auto*p=e?findParameter(*e,name):nullptr;if(!p||!std::isfinite(value)||value<p->minimum||value>p->maximum)throw std::invalid_argument("parameter invalid");p->value=value;}
Id EffectsEditor::addKeyframe(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId,std::string_view name,Rational time,double value,KeyframeInterpolation interpolation){auto*e=effect(s,t,id,effectId);auto*p=e?findParameter(*e,name):nullptr;const auto*item=t==EffectTarget::Item?s.findItem(id):nullptr;if(!p||time<Rational{}||(item&&time>item->duration)||!std::isfinite(value)||value<p->minimum||value>p->maximum)throw std::invalid_argument("keyframe invalid");auto duplicate=std::find_if(p->keyframes.begin(),p->keyframes.end(),[time](auto&k){return k.time==time;});if(duplicate!=p->keyframes.end()){duplicate->value=value;duplicate->interpolation=interpolation;return duplicate->id;}Keyframe key{.id=createId(),.time=time,.value=value,.interpolation=interpolation};auto result=key.id;p->keyframes.push_back(std::move(key));std::sort(p->keyframes.begin(),p->keyframes.end(),[](auto&a,auto&b){return a.time<b.time;});return result;}
void EffectsEditor::removeKeyframe(Sequence&s,EffectTarget t,std::string_view id,std::string_view effectId,std::string_view name,std::string_view keyId){auto*e=effect(s,t,id,effectId);auto*p=e?findParameter(*e,name):nullptr;if(!p)throw std::invalid_argument("parameter missing");const auto n=p->keyframes.size();std::erase_if(p->keyframes,[keyId](auto&k){return k.id==keyId;});if(n==p->keyframes.size())throw std::invalid_argument("keyframe missing");}
void EffectsEditor::pasteItemAttributes(Sequence&s,std::string_view sourceId,const std::vector<Id>& targets,bool useTransform,bool timing,bool useAudio,bool useEffects){const auto*source=s.findItem(sourceId);if(!source)throw std::invalid_argument("source missing");auto copy=*source;for(const auto&id:targets){auto*target=editableItem(s,id);if(!target||target->id==sourceId)continue;if(useTransform){target->transform=copy.transform;for(auto&channel:target->transform.animation)for(auto&key:channel.keyframes)key.id=createId();}if(timing){target->speed=copy.speed;target->pitchSemitones=copy.pitchSemitones;target->preservePitch=copy.preservePitch;target->reverse=copy.reverse;const auto ratio=Rational{static_cast<std::int64_t>(std::llround(copy.speed*1'000'000.0)),1'000'000};target->duration=target->sourceRange.duration()/ratio;target->freezeFrame=copy.freezeFrame&&target->sourceRange.contains(copy.freezeSourceTime);target->freezeSourceTime=target->freezeFrame?copy.freezeSourceTime:Rational{};}if(useAudio){target->audio=copy.audio;for(auto&key:target->audio.gainEnvelope)key.id=createId();for(auto&key:target->audio.panEnvelope)key.id=createId();}if(useEffects){target->effects=copy.effects;for(auto&e:target->effects){e.id=createId();for(auto&p:e.parameters)for(auto&k:p.keyframes)k.id=createId();}}}}
} // namespace ytp
